name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: #triggering the jobs according to predefined schedule
    - cron: 0 0 * * * #trigger once a day, according to the cron syntax

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v3
      - name: Build
        run: cd CLI && swift build
      - name: Run tests
        run: cd CLI && swift test